// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: searchcore.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_searchcore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searchcore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_searchcore_proto_rawDescGZIP(), []int{0}
}

func (x *IndexRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         int32                  `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_searchcore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchcore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_searchcore_proto_rawDescGZIP(), []int{1}
}

func (x *IndexResponse) GetDocId() int32 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *IndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_searchcore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searchcore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_searchcore_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         int32                  `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_searchcore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_searchcore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_searchcore_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResult) GetDocId() int32 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_searchcore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchcore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_searchcore_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         int32                  `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_searchcore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searchcore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_searchcore_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetDocId() int32 {
	if x != nil {
		return x.DocId
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_searchcore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchcore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_searchcore_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_searchcore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searchcore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_searchcore_proto_rawDescGZIP(), []int{7}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalDocs     int32                  `protobuf:"varint,1,opt,name=total_docs,json=totalDocs,proto3" json:"total_docs,omitempty"`
	TotalTerms    int32                  `protobuf:"varint,2,opt,name=total_terms,json=totalTerms,proto3" json:"total_terms,omitempty"`
	AvgDocLength  float32                `protobuf:"fixed32,3,opt,name=avg_doc_length,json=avgDocLength,proto3" json:"avg_doc_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_searchcore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchcore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_searchcore_proto_rawDescGZIP(), []int{8}
}

func (x *StatsResponse) GetTotalDocs() int32 {
	if x != nil {
		return x.TotalDocs
	}
	return 0
}

func (x *StatsResponse) GetTotalTerms() int32 {
	if x != nil {
		return x.TotalTerms
	}
	return 0
}

func (x *StatsResponse) GetAvgDocLength() float32 {
	if x != nil {
		return x.AvgDocLength
	}
	return 0
}

var File_searchcore_proto protoreflect.FileDescriptor

const file_searchcore_proto_rawDesc = "" +
	"\n" +
	"\x10searchcore.proto\x12\n" +
	"searchcore\"(\n" +
	"\fIndexRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"Z\n" +
	"\rIndexResponse\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\x05R\x05docId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\":\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"U\n" +
	"\fSearchResult\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\x05R\x05docId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\"Z\n" +
	"\x0eSearchResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.searchcore.SearchResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"&\n" +
	"\rDeleteRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\x05R\x05docId\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0e\n" +
	"\fStatsRequest\"u\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"total_docs\x18\x01 \x01(\x05R\ttotalDocs\x12\x1f\n" +
	"\vtotal_terms\x18\x02 \x01(\x05R\n" +
	"totalTerms\x12$\n" +
	"\x0eavg_doc_length\x18\x03 \x01(\x02R\favgDocLength2\x9d\x02\n" +
	"\rSearchService\x12D\n" +
	"\rIndexDocument\x12\x18.searchcore.IndexRequest\x1a\x19.searchcore.IndexResponse\x12?\n" +
	"\x06Search\x12\x19.searchcore.SearchRequest\x1a\x1a.searchcore.SearchResponse\x12G\n" +
	"\x0eDeleteDocument\x12\x19.searchcore.DeleteRequest\x1a\x1a.searchcore.DeleteResponse\x12<\n" +
	"\x05Stats\x12\x18.searchcore.StatsRequest\x1a\x19.searchcore.StatsResponseB(Z&github.com/dhruvgorasiya/searchcore/pbb\x06proto3"

var (
	file_searchcore_proto_rawDescOnce sync.Once
	file_searchcore_proto_rawDescData []byte
)

func file_searchcore_proto_rawDescGZIP() []byte {
	file_searchcore_proto_rawDescOnce.Do(func() {
		file_searchcore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_searchcore_proto_rawDesc), len(file_searchcore_proto_rawDesc)))
	})
	return file_searchcore_proto_rawDescData
}

var file_searchcore_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_searchcore_proto_goTypes = []any{
	(*IndexRequest)(nil),   // 0: searchcore.IndexRequest
	(*IndexResponse)(nil),  // 1: searchcore.IndexResponse
	(*SearchRequest)(nil),  // 2: searchcore.SearchRequest
	(*SearchResult)(nil),   // 3: searchcore.SearchResult
	(*SearchResponse)(nil), // 4: searchcore.SearchResponse
	(*DeleteRequest)(nil),  // 5: searchcore.DeleteRequest
	(*DeleteResponse)(nil), // 6: searchcore.DeleteResponse
	(*StatsRequest)(nil),   // 7: searchcore.StatsRequest
	(*StatsResponse)(nil),  // 8: searchcore.StatsResponse
}
var file_searchcore_proto_depIdxs = []int32{
	3, // 0: searchcore.SearchResponse.results:type_name -> searchcore.SearchResult
	0, // 1: searchcore.SearchService.IndexDocument:input_type -> searchcore.IndexRequest
	2, // 2: searchcore.SearchService.Search:input_type -> searchcore.SearchRequest
	5, // 3: searchcore.SearchService.DeleteDocument:input_type -> searchcore.DeleteRequest
	7, // 4: searchcore.SearchService.Stats:input_type -> searchcore.StatsRequest
	1, // 5: searchcore.SearchService.IndexDocument:output_type -> searchcore.IndexResponse
	4, // 6: searchcore.SearchService.Search:output_type -> searchcore.SearchResponse
	6, // 7: searchcore.SearchService.DeleteDocument:output_type -> searchcore.DeleteResponse
	8, // 8: searchcore.SearchService.Stats:output_type -> searchcore.StatsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_searchcore_proto_init() }
func file_searchcore_proto_init() {
	if File_searchcore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_searchcore_proto_rawDesc), len(file_searchcore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_searchcore_proto_goTypes,
		DependencyIndexes: file_searchcore_proto_depIdxs,
		MessageInfos:      file_searchcore_proto_msgTypes,
	}.Build()
	File_searchcore_proto = out.File
	file_searchcore_proto_goTypes = nil
	file_searchcore_proto_depIdxs = nil
}
